# Generated by Django 2.2 on 2020-09-27 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toDoApi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='groupings',
        ),
    ]
