# Generated by Django 2.2 on 2020-09-28 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toDoApi', '0002_delete_groupings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='toDo',
            new_name='toDoDiscrip',
        ),
    ]
