# Generated by Django 2.2 on 2020-09-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDoApi', '0004_auto_20200928_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
