# Generated by Django 2.2 on 2020-09-28 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toDoApi', '0005_auto_20200928_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='date',
        ),
    ]
